name: Release NPM Package

on:
  push:
    tags:
      - "v*"

jobs:
  test:
    uses: ./.github/workflows/test.yml

  release:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "20"
          registry-url: "https://registry.npmjs.org"
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Update version in package.json
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          pnpm version ${VERSION#v} --no-git-tag-version
      - name: Publish to NPM
        run: pnpm publish --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Update new version to package.json
        run: |
          git config --local user.email "root@wuchuheng.com"
          git config --local user.name "wuchuheng"
          VERSION=${GITHUB_REF#refs/tags/}
          git add package.json
          git commit -m "Bump version to ${VERSION#v}"
          git push
