name: Test Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest # This can be any GitHub-hosted runner
    env:
      CONTAINER_NAME: "ubuntu-22-04"

    steps:
      - name: Run the container
        run: |
          docker run -itd --name ${CONTAINER_NAME} ubuntu:22.04
            docker exec ${CONTAINER_NAME} bash -c "
              apt-get update
              apt-get install -y curl git  # Add any other packages you need
            "
      - name: Install node
        run: |
          docker exec ${CONTAINER_NAME} bash -c "
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | bash

            # Set up the nvm environment for the base environment.
            echo 'export NVM_DIR="$HOME/.nvm"' >> ~/.bashrc
            echo '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm' >> ~/.bashrc

            # Reload the bash environment.
            source ~/.bashrc

            # Install node
            nvm install 20.17.0
            nvm alias default 20.17.0
            nvm use 20.17.0
            node -v
          "
      - name: Install pnpm
        run: |
          docker exec ${CONTAINER_NAME} bash -c "
            npm install -g pnpm
            pnpm -v
          "
      - name: Test the cli
        run: |
          docker exec ${CONTAINER_NAME} bash -c "
            echo y | npx @wuchuheng/express my-app
          "
      # # Update and install necessary packages
      # - name: Update and install dependencies
      #   run: |
      # - name: Install nvm and the version v20.17.0 of node.
      #   run: |
      #     # 1. Install node
      #     curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | bash
      #     # Set up the node environment for the workflow.
      #     export NVM_DIR="$HOME/.nvm"
      #     [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
      #     nvm install 20.17.0
      #     nvm alias default 20.17.0
      #     nvm use 20.17.0

      #     ls -ahl $NVM_DIR/versions/node/v20.17.0/bin

      #     echo "The node version is $(node -v)"
      #     echo "The npm version is $(npm -v)"

      #     # 2. Create a new directory as the workspace.
      #     mkdir my-workspace
      #     cd my-workspace

      #     # 3. Install pnpm
      #     npm install -g pnpm
      #     # 4. Test the cli.
      #     echo $SHELL
      #     echo y | npx @wuchuheng/express my-app
