name: Test Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest # This can be any GitHub-hosted runner
    container:
      image: ubuntu:22.04

    steps:
      - uses: actions/checkout@v3
      # Update and install necessary packages
      - name: Update and install dependencies
        run: |
          apt-get update
          apt-get install -y curl git  # Add any other packages you need
      - name: Install nvm and the version v20.17.0 of node.
        run: |
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | bash
          echo "NVM_DIR=\"$([ -z \"${XDG_CONFIG_HOME-}\" ] && printf %s \"${HOME}/.nvmn" || printf %s \"${XDG_CONFIG_HOME}/nvm\")\"" >> $GITHUB_ENV
          # echo "[ -s \"$NVM_DIR/nvm.sh\" ] && \. \"$NVM_DIR/nvm.sh\"" >> $GITHUB_ENV
      - name: Install node v20.17.0
        run: |
          node -v
          nvm install 20.17.0
          nvm alias default 20.17.0

      # - name: Set up the node environment for the workflow.
      #   run: |
      #     nvm use

      # - name: Install pnpm
      #   run: |
      #     curl -fsSL https://get.pnpm.io/install.sh | sh -
      #     export PATH=$PATH:$HOME/.pnpm-global/bin

      # - name: Clean up all files.
      #   run: |
      #     rm -rf ./* ./.*
      #     ls -ahl
