name: Test Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest # This can be any GitHub-hosted runner
    container:
      image: ubuntu:22.04
      options: --entrypoint /bin/bash # Set Bash as the default shell

    steps:
      - uses: actions/checkout@v3
      # Update and install necessary packages
      - name: Update and install dependencies
        run: |
          apt-get update
          apt-get install -y curl git  # Add any other packages you need
      - name: Install nvm and the version v20.17.0 of node.
        run: |
          # 1. Install node
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | bash
          # Set up the node environment for the workflow.
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
          nvm install 20.17.0
          nvm alias default 20.17.0
          nvm use 20.17.0

          ls -ahl $NVM_DIR/versions/node/v20.17.0/bin

          echo "The node version is $(node -v)"
          echo "The npm version is $(npm -v)"

          # 2. Create a new directory as the workspace.
          mkdir my-workspace
          cd my-workspace

          # 3. Install pnpm
          npm install -g pnpm
          # 4. Test the cli.
          echo $SHELL
          echo y | npx @wuchuheng/express my-app
